# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Checkout ACore
      uses: rohmanngmbh/action-checkout-repo@v1.3.5
      with:
        # Repository name with owner. For example, actions/checkout
        repository: araxiaonline/AzerothCore-wotlk-with-NPCBots
        path: AzerothCore
    - name: Checkout mod-auctionator
      uses: rohmanngmbh/action-checkout-repo@v1.3.5
      with:
        path: AzerothCore/modules/mod-auctionator

    - name: List Files
      working-directory: ${{github.workspace}}/AzerothCore
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ls -al

